name: Benchmark All

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  evilbot:
    uses: ./.github/workflows/benchmark-publish.yaml
    with:
      opponent: EvilBot
      threads: 5
      jobs: 10

  stockfish:
    uses: ./.github/workflows/benchmark-publish.yaml
    strategy:
      matrix:
        level: [0, 2, 5]
    with:
      opponent: Stockfish
      opponent_long: Stockfish (${{ matrix.level }})
      threads: 5
      jobs: 10
      fens: 250
      run: |
        cd Chess-Challenge
        wget -nv https://github.com/official-stockfish/Stockfish/releases/download/sf_16/stockfish-ubuntu-x86-64-avx2.tar
        tar -xf stockfish-ubuntu-x86-64-avx2.tar
        echo "STOCKFISH_BIN=stockfish/stockfish-ubuntu-x86-64-avx2" >> $GITHUB_ENV
        echo "STOCKFISH_LEVEL=${{ matrix.level }}" >> $GITHUB_ENV
