---
name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  python-lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pre-commit
      - name: Execute checks
        run: pre-commit run --all-files --show-diff-on-failure
