name: Release

on:

  workflow_dispatch:
    inputs:
      new_engine_version:
        description: 'New engine version. If empty, run number will be used and no commit/tag/release will be created'
        default: ''
        required: false
      should_commit_new_version:
        description: 'Commit and push version increment. If true, this new commit will be the one tagged (in case Tag version release is also set to true)'
        type: boolean
        default: true
        required: false
      should_tag_new_version:
        description: 'Tag version release. If false, no release will be created either'
        type: boolean
        default: true
        required: false
      should_create_github_release:
        description: 'Create GitHub Release'
        type: boolean
        default: true
        required: false

env:
  DOTNET_VERSION: 8.x
  BOT_NAME: TeenyLynx
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  publish-code:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Nuget cache
      uses: actions/cache@v3
      with:
        path:
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Set version to ${{ github.event.inputs.new_engine_version }}
      shell: pwsh
      run: |
        $input_path = "Directory.Build.props"
        $regex = "(?<=<Version>).*(?=</Version>)"
        (Get-Content $input_path) -Replace $regex, '${{ github.event.inputs.new_engine_version }}' | Out-File $input_path

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage" -v normal

    - name: Upload ${{ env.BOT_NAME }}-${{ github.event.inputs.new_engine_version }} source code
      if: github.event.inputs.new_engine_version != ''
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BOT_NAME }}-${{ github.event.inputs.new_engine_version }}
        path: |
          Chess-Challenge/src/My Bot/*.cs
        if-no-files-found: error

  publish-uci:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        runtime-identifier: [win-x64, win-arm64, linux-x64, linux-arm64, linux-arm, osx-x64, osx.11.0-arm64, osx.12-arm64, osx.13-arm64]
        include:
          - runtime-identifier: win-x64
            os: windows-latest
          - runtime-identifier: win-arm64
            os: windows-latest
          - runtime-identifier: linux-x64
            os: ubuntu-latest
          - runtime-identifier: linux-arm64
            os: ubuntu-latest
          - runtime-identifier: linux-arm
            os: ubuntu-latest
          - runtime-identifier: osx-x64
            os: ubuntu-latest
          - runtime-identifier: osx.11.0-arm64
            os: ubuntu-latest
          - runtime-identifier: osx.12-arm64
            os: ubuntu-latest
          - runtime-identifier: osx.13-arm64
            os: ubuntu-latest
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Nuget cache
      uses: actions/cache@v3
      with:
        path:
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Set version to ${{ github.event.inputs.new_engine_version }}
      shell: pwsh
      run: |
        $input_path = "Directory.Build.props"
        $regex = "(?<=<Version>).*(?=</Version>)"
        (Get-Content $input_path) -Replace $regex, '${{ github.event.inputs.new_engine_version }}' | Out-File $input_path

    - name: Publish ${{ matrix.runtime-identifier }} version
      run: dotnet publish TeenyLynx.UCI/TeenyLynx.UCI.csproj -c Release --runtime ${{ matrix.runtime-identifier }} --self-contained /p:Optimized=true /p:DeterministicBuild=true /p:UCI=true -o artifacts/${{ matrix.runtime-identifier }}

    - name: Upload ${{ env.BOT_NAME }}-${{ matrix.runtime-identifier }} artifact
      if: github.event.inputs.new_engine_version != ''
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BOT_NAME }}-${{ github.event.inputs.new_engine_version }}-${{ matrix.runtime-identifier }}
        path: |
          artifacts/${{ matrix.runtime-identifier }}/
          !artifacts/**/*.pdb
          !artifacts/**/*.runtimeconfig.json
          !artifacts/**/src
          !artifacts/**/resources
        if-no-files-found: error

    - name: Upload ${{ env.BOT_NAME }}-${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }}-${{ matrix.runtime-identifier }} artifact
      if: github.event.inputs.new_engine_version == ''
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BOT_NAME }}-${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }}-${{ matrix.runtime-identifier }}
        path: |
          artifacts/${{ matrix.runtime-identifier }}/
          !artifacts/**/*.pdb
          !artifacts/**/*.runtimeconfig.json
          !artifacts/**/src
          !artifacts/**/resources
        if-no-files-found: error

  release:
    needs: [publish-uci, publish-code]
    if: github.event.inputs.new_engine_version != ''

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure git user
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Set version to ${{ github.event.inputs.new_engine_version }}
      shell: pwsh
      run: |
        $input_path = "Directory.Build.props"
        $regex = "(?<=<Version>).*(?=</Version>)"
        (Get-Content $input_path) -Replace $regex, '${{ github.event.inputs.new_engine_version }}' | Out-File $input_path

    - name: Commit and push version increment
      if: github.event.inputs.should_commit_new_version == 'true'
      continue-on-error: true
      run: |
        git switch ${{ env.GITHUB_REF_SLUG }}
        git status
        git commit --allow-empty -am "🚀 Release v${{ github.event.inputs.new_engine_version }}"
        git push

    - name: Create git tag
      if: github.event.inputs.should_tag_new_version == 'true'
      run: |
        git switch ${{ env.GITHUB_REF_SLUG }}
        git status
        git tag -a v${{ github.event.inputs.new_engine_version }} -m "v${{ github.event.inputs.new_engine_version }}"
        git push --tags

    - uses: actions/download-artifact@v3
      with:
        path: artifacts/

    - name: Compress artifacts again
      if: github.event.inputs.should_create_github_release == 'true' && github.event.inputs.should_tag_new_version == 'true'
      run: for i in artifacts/${{ env.BOT_NAME }}-${{ env.GITHUB_REF_SLUG }}-*[!.cs]; do zip -0 -r -q -j "${i%/}.zip" "$i" & done; wait

    - name: Create GitHub release and upload assets
      if: github.event.inputs.should_create_github_release == 'true' && github.event.inputs.should_tag_new_version == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        assets=()
        for asset in artifacts/*.zip; do
          assets+=("-a" "$asset")
        done
        for asset in artifacts/${{ env.BOT_NAME }}-${{ github.event.inputs.new_engine_version }}/*.cs; do
          assets+=("-a" "$asset")
        done
        tag_name="v${{ github.event.inputs.new_engine_version }}"
        hub release create "${assets[@]}" --draft --message "$tag_name" "$tag_name"
